# Generated by Django 4.2.3 on 2023-08-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20230802_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
