# Generated by Django 4.2.3 on 2024-02-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_message_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
