# Generated by Django 4.2.3 on 2024-02-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_visit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
