# Generated by Django 4.2.3 on 2024-04-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_delete_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
